### PR TITLE
Qt5

### PR DESCRIPTION
**Pull request by pedromorgan**
I've converted as much as I can to Qt5, but really with no experience of the original game or ability to run.. I cannot really check..

There will be some qt4 elements hanging around, but the major changes are done and the sim "seems to work", and editor 

Can I suggest creating a "qt5" branch so changes can be targeted there..

Main snags is that there is no reset() method on the models.(marked with a FIXME)
http://doc.qt.io/qt-5/qabstractitemmodel-obsolete.html

So in some places I've created the reset() function (with a debug print), and in other places I've commented out with a FIXME. eg
https://github.com/pedromorgan/ts2/blob/qt5/ts2/editor/editorwindow.py#L295
and
https://github.com/pedromorgan/ts2/blob/qt5/ts2/trains/service.py#L104

For example QSortFilterProxyMode has no reset()..

### CODE REVIEW

**Comment by npiganeau** [comment]
Ok. I'll create a qt5 branch for porting to Qt5. 

I'll also rearrange the branches, because they are the wrong way round. Indeed, for now the master branch is the branch of the current release, and the development branch is V_0_5_BRANCH. So I'll make a 0.4 branch for the current release and we'll keep master for ongoing developments.

Note that I am actually quite close to releasing v0.5 which includes a really improved editor and a new implementation of signals (which should be enhanced in v0.6 with a signal editor). The remaining things to do is to port the simulations to this new version and test.

**Comment by pedromorgan** [comment]
Actually I think you would be doing that wrong..

- master = should be latest stable release.. this is the one that "distibutions" would use.. ie default latest/best
- develop = branch for "next gen" which when done would be merged into master..

Also "numbering" the branches is not good practise.. as these may conflict with tags.. and confuse users... (we had this nightmare with FlightGear)..

anyway.. some thoughts.. :-)

**Comment by npiganeau** [comment]
Ok, then. I've done all you suggested !

Now for the code itself, the reset function was called to force the update of the different views in the docks when a train was selected either on the scene or on the train list view. Same goes for the selection of a service in the service list view.

I guess this was quite a dirty hack. If it works without, then it is for the best. Otherwise, we'll need to find a way to get the views updated correctly.

**Comment by npiganeau** [comment]
I've just ported the develop branch to Qt5, so I close this PR. Thanks for your help.

**Pull request closed without merging**
